### ISSUE TITLE
features to build an "expert" dataset

### ISSUE THREAD

**Issue by morgangiraud** [SerpentAI/SerpentAI#117]
Hi,

I have a new usecase, I need a way to construct an expert dataset to do imitation learning. 
More and more papers are coming out showing that this is an easy way to speed up the training of a bot removing the usual first completely random exploration out of the way or at least mitigating it.
Basically it can be used as an initialisation of the NN before starting self-play.

I believe adding a process to serpentai to construct such a dataset in an easy way could be a wonderful feature. I noticed that you wanted to do analytics, there might be some overlap there so I wanted to ask the question first.

Here is my idea of a decent workflow:
- Launch the game (ok)
- Launch a real-time capture at 30 fps storing frames and key pressed (some kind of a keylogger)
- Consolidating the two stream of data into one easy-to-use generic format.

A user would have to build a function that translate this format into a working datasets for its bot on the fly.
In the mean time, this stream could be used to compute all sorts of analytics too, the one that I see as very interesting is APM. It would allow one to experimentally set the bot APM for a given game.

**Comment by nbrochu** [comment]
This is the current feature I am working on and it's mostly working already! :D

**Comment by dbsxdbsx** [comment]
@nbrochu really? Is it done now? How to do it ?  I didnot see tutorial in wiki.

**Comment by nbrochu** [comment]
Unreleased. The next version is going to be big, but that also mean I have a ton of work when it comes to testing and documentation.

The way it will work is like this: You fully build your experiment, let's say with a random agent, complete with the ability to reward it and start new episodes in the environment. You can then swap the random agent with a new recorder agent and start it. Your experiment will be automated as usual but you can play during an episode and it will record your input with the frames, rewards and terminal states. It all gets stored in an HDF5 file between episodes. When you are done, you can replace the recorder agent with an agent that supports human bootstraps like the rainbow DQN agent and it will automatically populate it's replay memory with the human observations.

It takes a good amount of time between releases but I take great care in making it as pleasant to work with as possible.

**Comment by dbsxdbsx** [comment]
@nbrochu , thanks for your supprot on this suggestion. According to what you stated, it seems that soon we can treat ourselves as the "behavior agent" with Q-learning. And this mechanism would really accelerate  agent to achieve optimal policy, since we could only run one instance at a  time for a game with SerpentAI.

In addition , I have one question and one advice.
Qustion :  Using SerpentAI with reinforcement learning, how to set rewards for a specific state in a video game episode,  besides digging out memory, I guess the only way out is  OCR with context-classifier?

Advice : For imitation learning, I know some games would hook keyboard  or even mouse input---For successfully collect data, hope this issue could be well handled. Thanks.
