### ISSUE TITLE
Could Tensorflow be separated from "serpent setup"?

### ISSUE THREAD

**Issue by dbsxdbsx** [SerpentAI/SerpentAI#122]
I tried to set SerpentAI yesterday following Wiki on Win10. When choosing `GPU`  with  `serpent setup`, it would automatically download tensorflow gpu veriosn. I wonder whether it is possible to  skip this step, because I installed some other deep learning framework.

**Comment by nbrochu** [comment]
Tensorflow is installed because some of the algorithms that are bundled with Serpent.AI use it. You can use any other framework (PyTorch, MXNet, Caffe etc.) you desire inside your game agents. `tensorflow-gpu` is actually a very small library. If you really want it gone you can just `pip uninstall tensorflow-gpu`.

I will not be removing it from the dependencies since some features in Serpent.AI use it.
