### ISSUE TITLE
The main SHORTCOMING of SerpentAI is it cannot be trained concurrently

### ISSUE THREAD

**Issue by dbsxdbsx** [SerpentAI/SerpentAI#178]
I know SerpentAI is really a wonderful project to train custom AI for custom game. It can also identify different game context , with which different scripts could be applied to.

But with reinforcement learning, it is too inefficient at present.  For example the algorithm A3C,  it needs several agents to play games concurrently.  But how could that be done with SerpentAI?   Seems no way at present.

So I  wonder whether there is a way that SerpentAI could turn game into backstage, and make several same game objects launched concurrently.
From a technical point of view, I know this is very difficult. Because I've tried it on windows. I know there are merely program allowing itself be launched with more than one process. 

But for SerpentAI ,it is just so nearly perfect but only with this drawback.

**Comment by nbrochu** [comment]
Even if you could run multiple instances of a game, interact with them and use something like A3C (which isn't that good and has mostly been abandoned, although it inspired a lot of a good actor-critic approaches), our consumer hardware could not handle it. A single agent that trains 8 times per second with a reasonable 32 batch size maxes out a GTX 1080ti with 100x100x4 grayscale input. Having more agents won't solve anything.

This is a reinforcement learning problem (i.e. training is extremely sample inefficient and compute expensive) more than it is a Serpent.AI problem. I respect your opinion but the reality is that unless you are well-funded with brilliant researchers like DeepMind or OpenAI, the training "speed" your are getting with Serpent.AI is what is within the reach of a normal individual at the moment. Add this to the fact that all top performing approaches with actual implementations (i.e. not theoretical or an unimplemented paper) at the moment are single-agent.

It's good food for thought but I'm going to close this because it isn't an issue per se. Thanks!
