### ISSUE TITLE
Update the macOS guide to use pyenv

### ISSUE THREAD

**Issue by nbrochu** [SerpentAI/SerpentAI#20]
For consistency.

**Comment by d0p3t** [comment]
The following guide may help with closing this issue. Since the Linux Installation Guide only refers to a _pyenv_ installer, this link may be used for the same effect. Actual _pyenv_ commands to setup the work environment should be the same as the Linux guide.


**Setting up Pyenv on OS X with Homebrew**
https://medium.com/@pimterry/setting-up-pyenv-on-os-x-with-homebrew-56c7541fd331

**Comment by d0p3t** [comment]
**Experiences Installing pyenv**

1. `brew install pyenv pyenv-virtualenv readline xz`
2. Add to your bash profile `~/.bashrc` (or in your  other terminal) -
```bash
# Start pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
source ~/.pyenv/completions/pyenv.bash # Support pyenv.bash pyenv.zsh pyenv.fish

# pyenv-virtualenv
if which pyenv-virtualenv-init > /dev/null; then
  eval "$(pyenv virtualenv-init -)";
fi
```
3. Create your virtual environment `pyenv virtualenv 3.6.2 serpent`
4. Create your project files directory `mkdir SerpentAI && cd SerpentAI` (any name, any location)
5. Initialize the new virtual environment `pyenv local serpent`
6. Done

Also to keep in mind is that for macOS users, by default `pip` and `python` will be linked to Python 2.7.2. I suggest to add aliases to your profile - `alias pip='pip3'` `alias python='python3'`. This will fix issues during `pip install SerpentAI`
