### ISSUE TITLE
A window size problem (macos)

### ISSUE THREAD

**Issue by atme** [SerpentAI/SerpentAI#30]
```sh
serpent play BitTripRunner SerpentBitTripRunnerGameAgent
{'width': 960, 'height': 542, 'x_offset': 0, 'y_offset': 42}
Traceback (most recent call last):
  File "/Users/atme/miniconda2/envs/serpent/bin/serpent", line 11, in <module>
    sys.exit(execute())
  File "/Users/atme/miniconda2/envs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 47, in execute
    command_function_mapping[command](*sys.argv[2:])
  File "/Users/atme/miniconda2/envs/serpent/lib/python3.6/site-packages/serpent/serpent.py", line 233, in play
    game.play(game_agent_class_name=game_agent_name, frame_handler=frame_handler)
  File "/Users/atme/miniconda2/envs/serpent/lib/python3.6/site-packages/serpent/game.py", line 157, in play
    game_frame = self.grab_latest_frame()
  File "/Users/atme/miniconda2/envs/serpent/lib/python3.6/site-packages/serpent/game.py", line 215, in grab_latest_frame
    3
  File "/Users/atme/miniconda2/envs/serpent/lib/python3.6/site-packages/serpent/frame_grabber.py", line 74, in get_frames
    frame_array = np.fromstring(frame_bytes, dtype="uint8").reshape(frame_shape)
ValueError: cannot reshape array of size 6243840 into shape (542,960,3)
```

**Comment by atme** [comment]
For some reason it is a mss problem. The library grabs a screenshot with 1920x1084 size although the window size is 960x542. Don't know yet how I can fix it.
Mss version is 3.0.1

**Comment by d0p3t** [comment]
**This is an issue related to Retina displays**

There is currently an discussion going on to try and find the best solution for this issue. 

The framework has to detect whether you are using a Retina display, and if so, size down the frame grabbed by 50%. An implementation was suggested [here](https://github.com/SerpentAI/SerpentAI/pull/17), but is not according to the code style, so it will be fixed in the next update (the pull request also has comments regarding the progress).

This was the [proposed implementation](https://github.com/SerpentAI/SerpentAI/pull/17/commits/6b9fd0137da58ee13372511b196d09d150e2dc7b). If you're feeling groovy, you can compile the framework yourself with
(frame_grabber.py ~L69-70)
```python
if sys.platform == "darwin":
    frame = scipy.misc.imresize(frame,0.5)
```
This, however, will allow you to only use retina displays.

**Comment by atme** [comment]
Yeah, the code solutes the bug. Thanks.
Also I had to add two code lines at beginning of the file to run an agent:
```python
import sys
import scipy
```

**Comment by d0p3t** [comment]
Yes indeed. It works but only accounts for macos and assumes you only have a retina display. 

A better implementation will be released soon. Glad it works for you!
