### ISSUE TITLE
ScriptError during setup

### ISSUE THREAD

**Issue by vrishabcommuri** [SerpentAI/SerpentAI#45]
When running 'serpent play Game SerpentPlayerGameAgent' I get the following error:

applescript.ScriptError: System Events got an error: Can’t get window 1 of process "Game". Invalid index. (-1719) app='System Events' range=111-119

All of the previous commands of the setup run properly. I am on mac sunning Sierra 10.12.6.

**Comment by nbrochu** [comment]
In your game plugin, you need to change the window_name to the exact name of your game that you see in the title bar.

```python
class SerpentGame(Game, metaclass=Singleton):

    def __init__(self, **kwargs):
        kwargs["platform"] = "PLATFORM"

        kwargs["window_name"] = "WINDOW_NAME"  #  <=== This needs to match the title of the game window
```

**Comment by vrishabcommuri** [comment]
As far as I can tell, "WINDOW_NAME" is set correctly. I was able to reposition the window to (0,0) using the command 'serpent launch MyGame'. Could it be something else?

**Comment by nbrochu** [comment]
I have yet to setup a proper macOS install. The support was contributed. I'm gonna try to install it all on a MBP I have today and see what's up. Are you running a steam game I could use to try and reproduce the issue?

**Comment by vrishabcommuri** [comment]
Yes, the program that threw this error was Civilization V.

**Comment by nbrochu** [comment]
OK I got Serpent.AI going on my MPB. Gonna give Civ 5 a try.

**Comment by cschwartz** [comment]
I had a similar issue with SuperMeatBoy on macOS yesterday.
It turned out, the displayed window title does not necessarily equal the `window_id` `DarwinWindowController#is_window_focused` is expecting.

I was able to obtain the "correct" window title by running 

```AppleScript
delay 5
tell application "System Events"
    set focusedWindow to name of first application process whose frontmost is true
    return focusedWindow
end tell
```

in `Script Editor.App` and focussing the games window (the window_id will be printed in the results pane of Script Editor).

**Comment by nbrochu** [comment]
Yes I just experienced something wrong with is_window_focused on macOS.

I just changed the applescript to something that should let you use the window name you see.

```
global frontApp, frontAppName, windowTitle

set windowTitle to ""
tell application "System Events"
    set frontApp to first application process whose frontmost is true
    set frontAppName to name of frontApp
    set windowTitle to "no window"
    tell process frontAppName
        if exists (1st window whose value of attribute "AXMain" is true) then
            tell (1st window whose value of attribute "AXMain" is true)
                set windowTitle to value of attribute "AXTitle"
            end tell
        end if
    end tell
end tell

return windowTitle
```

**Comment by nbrochu** [comment]
Added here https://github.com/SerpentAI/SerpentAI/commit/a86544f7473a270ebed79dee7bd00523bb5b4287. I will push a new beta to PyPI soon.

And for that Civilization V example, It works for me with the following Game class:

```python
class SerpentCivVGame(Game, metaclass=Singleton):

    def __init__(self, **kwargs):
        kwargs["platform"] = "steam"

        kwargs["window_name"] = "Civilization V"

        kwargs["app_id"] = "8930"
        kwargs["app_args"] = None
        

        super().__init__(**kwargs)

        self.api_class = CivVAPI
        self.api_instance = None
```

I don't use `serpent launch` since it has a launcher window. I open it through Steam, then click play, let it load and then `serpent play CivV SerpentCivVGameAgent`

@cschwartz When you upgrade SerpentAI, you may have to change your window name to the one you see in the title bar with this new code.

**Comment by est** [comment]
wow I am also trying to play with SerpentAI rather than CIv5's own AI!
