### ISSUE TITLE
Window cannot focused

### ISSUE THREAD

**Issue by larry-fuy** [SerpentAI/SerpentAI#57]
This issue is related to the issue #50 . I set the windows name in the plugin code as the process name "UB2_steam". Now the plugin could run and put the game window into upper left corner. However when I run the "Hello World!" example, it only shows "PAUSED". I tried to search the repo and find the line https://github.com/SerpentAI/SerpentAI/blob/1bd837b854f4976ab20c93b3576603efc09b268a/serpent/game.py#L159 related to the issue. It seems the window is not focused. So is this a bug or I missed something?

**Comment by nbrochu** [comment]
Are you on latest SerpentAI? `pip install --upgrade SerpentAI`

**Comment by larry-fuy** [comment]
I upgraded to the latest version. Now it only solved problem partially. First, "Hello world" shows intermittently. When I focus the window manually, for example, click the mouse in the window, "Hello world" shows there. Otherwise, there is still only "PAUSED". Second, I added the visual debugger code after "Hello world" but it doesn't work.

**Comment by nbrochu** [comment]
`serpent play` will only be active when the focus in on the game window. This is by design to prevent it from doing unexpected stuff outside the game.

Otherwise, things like [this](https://www.twitch.tv/videos/137509018) can happen ;)

If you want step-by-step assistance, I suggest joining *#serpent-ai-help* on 
[Discord](https://discord.gg/9D5SuxH). Lots of people there to help (myself included)!
