### ISSUE TITLE
Raise ValueErrors on invalid inputs in serpent.py

### ISSUE THREAD

**Issue by nbrochu** [SerpentAI/SerpentAI#81]
Be stiff. Consistently.

**Comment by eriktaubeneck** [comment]
FWIW, [docopt](https://github.com/docopt/docopt/) makes this pretty explicit and you get the CLI menu-ing for free. Here's [an example](https://github.com/docopt/docopt/blob/master/examples/validation_example.py) for validating a specific type on the various inputs.

Also, if you wanted each command to have their own options/CLI menu-ing, [this project](https://github.com/gamechanger/dusty/tree/master/dusty/cli) is a good example of nesting docopt menus. (Disclaimer: I worked a bit on that project and for the company that built it, which is why I'm aware of it.)

As always, happy to help. 😃
